api = "0.2"

[buildpack]
  id = "paketo-community/ruby"
  name = "Ruby Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/mri"
    sha256 = "4d65299943f4bcc4e832d30a617b1d131e012f0e9562d3efe6327a30bfb11406"
    source = "https://github.com/paketo-community/mri/archive/v0.0.133.tar.gz"
    source_sha256 = "6e44f8c8d103c7da7376820054bc7aca8366d0fda387f909b72b7660600bbbe5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/mri/releases/download/v0.0.133/mri-0.0.133.tgz"
    version = "0.0.133"

  [[metadata.dependencies]]
    id = "paketo-community/bundler"
    sha256 = "146e42b003d3f91bfb5b119f809c10dcbaf8a69268d7e47f7f4a016d8fcc44e3"
    source = "https://github.com/paketo-community/bundler/archive/v0.0.119.tar.gz"
    source_sha256 = "0df90d1434e53893c301f5997767d46311c5929cf0b41997ac4b3b27e778813f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/bundler/releases/download/v0.0.119/bundler-0.0.119.tgz"
    version = "0.0.119"

  [[metadata.dependencies]]
    id = "paketo-community/bundle-install"
    sha256 = "d3d1cdfa4a177da5cc27007e5aab69fef61739ee63f2331ee458c61e95ce3830"
    source = "https://github.com/paketo-community/bundle-install/archive/v0.0.24.tar.gz"
    source_sha256 = "890e3c9662289c676d09c3aefd8ef786fb2bf093e4a8fd84119a4a2197be039f"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/bundle-install/releases/download/v0.0.24/bundle-install-0.0.24.tgz"
    version = "0.0.24"

  [[metadata.dependencies]]
    id = "paketo-community/puma"
    sha256 = "5a3fdb872e94e629bdee9cff083e286502bee061c9132f574de25cb7c68131e7"
    source = "https://github.com/paketo-community/puma/archive/v0.0.17.tar.gz"
    source_sha256 = "40cf186522a6baee3987fd63b4d7566d96519ab495af68906701c8131d76e41a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/puma/releases/download/v0.0.17/puma-0.0.17.tgz"
    version = "0.0.17"

  [[metadata.dependencies]]
    id = "paketo-community/thin"
    sha256 = "473bc049bab6f3bcb2fab203e4b0cfd2489bf1592ceb766b4f529f061449edc6"
    source = "https://github.com/paketo-community/thin/archive/v0.0.13.tar.gz"
    source_sha256 = "64ed3d4adb4011a3636e539aab4a3677c040bb8c4cd47d8bfddd8b635a2b2a9a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/thin/releases/download/v0.0.13/thin-0.0.13.tgz"
    version = "0.0.13"

  [[metadata.dependencies]]
    id = "paketo-community/unicorn"
    sha256 = "c7d83b6d37e50b28efe21f312519cfe94ee3da7a7d0db0ff876650c5e74ba130"
    source = "https://github.com/paketo-community/unicorn/archive/v0.0.10.tar.gz"
    source_sha256 = "5b360daa71200c45d4f4a9567a041c368fb76d4f7b98e43082a3bf2b4157ff35"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/unicorn/releases/download/v0.0.10/unicorn-0.0.10.tgz"
    version = "0.0.10"

  [[metadata.dependencies]]
    id = "paketo-community/rackup"
    sha256 = "1d8e6074f15bdca90584929c27cbfe266ed2e5743418bffb0512aebadbcda3a2"
    source = "https://github.com/paketo-community/rackup/archive/v0.0.15.tar.gz"
    source_sha256 = "d3440304db4c0300baedd7e3e4361d2e4da81eac535de2d61eecc83dfe3331cd"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/rackup/releases/download/v0.0.15/rackup-0.0.15.tgz"
    version = "0.0.15"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.133"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.119"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.24"

  [[order.group]]
    id = "paketo-community/puma"
    version = "0.0.17"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.133"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.119"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.24"

  [[order.group]]
    id = "paketo-community/thin"
    version = "0.0.13"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.133"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.119"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.24"

  [[order.group]]
    id = "paketo-community/unicorn"
    version = "0.0.10"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.133"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.119"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.24"

  [[order.group]]
    id = "paketo-community/rackup"
    version = "0.0.15"
