api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/ruby"
  id = "paketo-buildpacks/ruby"
  name = "Paketo Ruby Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.162"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.151"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.58"

  [[order.group]]
    id = "paketo-community/puma"
    version = "0.0.48"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "2.0.2"
    optional = true

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.162"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.151"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.58"

  [[order.group]]
    id = "paketo-buildpacks/thin"
    version = "0.0.45"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "2.0.2"
    optional = true

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.162"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.151"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.58"

  [[order.group]]
    id = "paketo-community/unicorn"
    version = "0.0.42"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "2.0.2"
    optional = true

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.162"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.151"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.58"

  [[order.group]]
    id = "paketo-community/passenger"
    version = "0.0.9"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "2.0.2"
    optional = true

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.162"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.151"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.58"

  [[order.group]]
    id = "paketo-community/rackup"
    version = "0.0.46"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "2.0.2"
    optional = true

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.162"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.151"
    optional = true

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.58"
    optional = true

  [[order.group]]
    id = "paketo-community/rake"
    version = "0.0.4"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "2.0.2"
    optional = true
