api = "0.2"

[buildpack]
  id = "paketo-community/ruby"
  name = "Ruby Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/mri"
    sha256 = "1d41393f67b22055d0263bb4a8e67972c5550fb5812c4d276496182864110466"
    source = "https://github.com/paketo-community/mri/archive/v0.0.140.tar.gz"
    source_sha256 = "2f713f0c8a148f2b9f9bf91b765f76f003d221d54030871ad3e59ff55afd574f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/mri/releases/download/v0.0.140/mri-0.0.140.tgz"
    version = "0.0.140"

  [[metadata.dependencies]]
    id = "paketo-community/bundler"
    sha256 = "6e3594e3d02cc2ab0e1803fec62d3f61a6787606a649808c52706ae1a94a1a26"
    source = "https://github.com/paketo-community/bundler/archive/v0.0.129.tar.gz"
    source_sha256 = "06f5cb515061a980957e4a6efde596dc29e63ed18be657f3133e5b57d275e165"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/bundler/releases/download/v0.0.129/bundler-0.0.129.tgz"
    version = "0.0.129"

  [[metadata.dependencies]]
    id = "paketo-community/bundle-install"
    sha256 = "8f9fd708963b642a0a43d4b7bdcde6878f5c6559605fcc9969ce6888dd06cc20"
    source = "https://github.com/paketo-community/bundle-install/archive/v0.0.31.tar.gz"
    source_sha256 = "2f01ecd39d3e3ca65ac1c306b34037127a95c2f4be3871ddfc26f9a4b03d2c98"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/bundle-install/releases/download/v0.0.31/bundle-install-0.0.31.tgz"
    version = "0.0.31"

  [[metadata.dependencies]]
    id = "paketo-community/puma"
    sha256 = "e31048ec0afaa1dbee6284b71e874f12fbcd3a71a73888467484f120bea23e68"
    source = "https://github.com/paketo-community/puma/archive/v0.0.22.tar.gz"
    source_sha256 = "32ac75be0ba5bfa2ade73bb7c0805ce70d6817844544a4d1046b4910a8d5636a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/puma/releases/download/v0.0.22/puma-0.0.22.tgz"
    version = "0.0.22"

  [[metadata.dependencies]]
    id = "paketo-community/thin"
    sha256 = "e7621b3ab5c8d3284c17b597d1bd2a05c4f0ea0e4f92583b6db3a0cf6c85e25a"
    source = "https://github.com/paketo-community/thin/archive/v0.0.19.tar.gz"
    source_sha256 = "fdd4e856ff094b954830d7171c09ad3c4affb65a70375de0b46c736594b2d271"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/thin/releases/download/v0.0.19/thin-0.0.19.tgz"
    version = "0.0.19"

  [[metadata.dependencies]]
    id = "paketo-community/unicorn"
    sha256 = "9f246d65e64d28c42ba1de94ce61202f45546dca9ac0c81ba908b88ef3fb3f7f"
    source = "https://github.com/paketo-community/unicorn/archive/v0.0.17.tar.gz"
    source_sha256 = "ad6ae2e0e85029f406e727b98df65cfd9d2ceb471d6792020610ae901ebb9369"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/unicorn/releases/download/v0.0.17/unicorn-0.0.17.tgz"
    version = "0.0.17"

  [[metadata.dependencies]]
    id = "paketo-community/rackup"
    sha256 = "eb42e5e269a6322dc3b83691e4e9e988348d3f44f07327429e3ab5dac6ccecd8"
    source = "https://github.com/paketo-community/rackup/archive/v0.0.23.tar.gz"
    source_sha256 = "bb8562839414d30749e4d1986f1d202c8b8f8473a9b60f2a48e7fca28b739eee"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/rackup/releases/download/v0.0.23/rackup-0.0.23.tgz"
    version = "0.0.23"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.140"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.129"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.31"

  [[order.group]]
    id = "paketo-community/puma"
    version = "0.0.22"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.140"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.129"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.31"

  [[order.group]]
    id = "paketo-community/thin"
    version = "0.0.19"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.140"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.129"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.31"

  [[order.group]]
    id = "paketo-community/unicorn"
    version = "0.0.17"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.140"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.129"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.31"

  [[order.group]]
    id = "paketo-community/rackup"
    version = "0.0.23"
