api = "0.7"

[buildpack]
  description = "A language family buildpack for building Ruby apps"
  homepage = "https://github.com/paketo-buildpacks/ruby"
  id = "paketo-buildpacks/ruby"
  keywords = ["ruby"]
  name = "Paketo Buildpack for Ruby"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/ruby/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.10.4"

  [[order.group]]
    id = "paketo-buildpacks/mri"
    version = "0.17.37"

  [[order.group]]
    id = "paketo-buildpacks/bundler"
    version = "0.8.48"

  [[order.group]]
    id = "paketo-buildpacks/bundle-install"
    version = "0.8.18"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true
    version = "7.7.0"

  [[order.group]]
    id = "paketo-buildpacks/yarn"
    optional = true
    version = "2.2.3"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    optional = true
    version = "2.6.3"

  [[order.group]]
    id = "paketo-buildpacks/rails-assets"
    optional = true
    version = "0.10.25"

  [[order.group]]
    id = "paketo-buildpacks/puma"
    version = "0.4.60"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.3"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.3"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.10.4"

  [[order.group]]
    id = "paketo-buildpacks/mri"
    version = "0.17.37"

  [[order.group]]
    id = "paketo-buildpacks/bundler"
    version = "0.8.48"

  [[order.group]]
    id = "paketo-buildpacks/bundle-install"
    version = "0.8.18"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true
    version = "7.7.0"

  [[order.group]]
    id = "paketo-buildpacks/yarn"
    optional = true
    version = "2.2.3"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    optional = true
    version = "2.6.3"

  [[order.group]]
    id = "paketo-buildpacks/rails-assets"
    optional = true
    version = "0.10.25"

  [[order.group]]
    id = "paketo-buildpacks/thin"
    version = "0.5.56"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.3"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.3"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.10.4"

  [[order.group]]
    id = "paketo-buildpacks/mri"
    version = "0.17.37"

  [[order.group]]
    id = "paketo-buildpacks/bundler"
    version = "0.8.48"

  [[order.group]]
    id = "paketo-buildpacks/bundle-install"
    version = "0.8.18"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true
    version = "7.7.0"

  [[order.group]]
    id = "paketo-buildpacks/yarn"
    optional = true
    version = "2.2.3"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    optional = true
    version = "2.6.3"

  [[order.group]]
    id = "paketo-buildpacks/rails-assets"
    optional = true
    version = "0.10.25"

  [[order.group]]
    id = "paketo-buildpacks/unicorn"
    version = "0.4.59"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.3"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.3"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.10.4"

  [[order.group]]
    id = "paketo-buildpacks/mri"
    version = "0.17.37"

  [[order.group]]
    id = "paketo-buildpacks/bundler"
    version = "0.8.48"

  [[order.group]]
    id = "paketo-buildpacks/bundle-install"
    version = "0.8.18"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true
    version = "7.7.0"

  [[order.group]]
    id = "paketo-buildpacks/yarn"
    optional = true
    version = "2.2.3"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    optional = true
    version = "2.6.3"

  [[order.group]]
    id = "paketo-buildpacks/rails-assets"
    optional = true
    version = "0.10.25"

  [[order.group]]
    id = "paketo-buildpacks/passenger"
    version = "0.14.14"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.3"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.3"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.10.4"

  [[order.group]]
    id = "paketo-buildpacks/mri"
    version = "0.17.37"

  [[order.group]]
    id = "paketo-buildpacks/bundler"
    version = "0.8.48"

  [[order.group]]
    id = "paketo-buildpacks/bundle-install"
    version = "0.8.18"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true
    version = "7.7.0"

  [[order.group]]
    id = "paketo-buildpacks/yarn"
    optional = true
    version = "2.2.3"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"
    optional = true
    version = "2.6.3"

  [[order.group]]
    id = "paketo-buildpacks/rails-assets"
    optional = true
    version = "0.10.25"

  [[order.group]]
    id = "paketo-buildpacks/rackup"
    version = "0.4.52"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.3"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.3"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.10.4"

  [[order.group]]
    id = "paketo-buildpacks/mri"
    version = "0.17.37"

  [[order.group]]
    id = "paketo-buildpacks/bundler"
    optional = true
    version = "0.8.48"

  [[order.group]]
    id = "paketo-buildpacks/bundle-install"
    optional = true
    version = "0.8.18"

  [[order.group]]
    id = "paketo-buildpacks/rake"
    version = "0.4.61"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.3"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.3"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.2"
