api = "0.2"

[buildpack]
  id = "paketo-community/ruby"
  name = "Ruby Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.148"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.135"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.40"

  [[order.group]]
    id = "paketo-community/puma"
    version = "0.0.31"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "1.3.10"
    optional = true

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.148"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.135"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.40"

  [[order.group]]
    id = "paketo-community/thin"
    version = "0.0.28"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "1.3.10"
    optional = true

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.148"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.135"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.40"

  [[order.group]]
    id = "paketo-community/unicorn"
    version = "0.0.26"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "1.3.10"
    optional = true

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.148"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.135"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.40"

  [[order.group]]
    id = "paketo-community/rackup"
    version = "0.0.30"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "1.3.10"
    optional = true
