api = "0.2"

[buildpack]
  id = "paketo-community/ruby"
  name = "Ruby Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/mri"
    sha256 = "c2e5d876ec07f143efd10c05cdd01abb26117221cd44c96722a1cd9b4e2dafbb"
    source = "https://github.com/paketo-community/mri/archive/v0.0.135.tar.gz"
    source_sha256 = "c6dfefb2ba3af09b83bac97e5399c73674eabf815ea157dda6c57834eb7757b0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/mri/releases/download/v0.0.135/mri-0.0.135.tgz"
    version = "0.0.135"

  [[metadata.dependencies]]
    id = "paketo-community/bundler"
    sha256 = "4fd78f4f315bcb88ac657c9ee59e040b6cbbde3adcae6389bea9a3db0d141d5b"
    source = "https://github.com/paketo-community/bundler/archive/v0.0.122.tar.gz"
    source_sha256 = "b769d6c2f5c2711d5dafeb7c509332d4851c577eaccff5ace3ace25a3dee4f40"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/bundler/releases/download/v0.0.122/bundler-0.0.122.tgz"
    version = "0.0.122"

  [[metadata.dependencies]]
    id = "paketo-community/bundle-install"
    sha256 = "19c7684de5c5f4d445b70fc2b39de960aef041111e471eb3569264129c6f9105"
    source = "https://github.com/paketo-community/bundle-install/archive/v0.0.26.tar.gz"
    source_sha256 = "dfe99a4deda10ecdc0495331caccc83a250b354f1f84d6369036e336bfde6735"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/bundle-install/releases/download/v0.0.26/bundle-install-0.0.26.tgz"
    version = "0.0.26"

  [[metadata.dependencies]]
    id = "paketo-community/puma"
    sha256 = "3c568f12bdb81dcbb87cc602937df460c5e1b570bcad6cedadfe1c27b38faa8a"
    source = "https://github.com/paketo-community/puma/archive/v0.0.18.tar.gz"
    source_sha256 = "450c42c9913115c58fad0db1392376179c1d05ffb5f9a4a3e065aaf7a6a0f797"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/puma/releases/download/v0.0.18/puma-0.0.18.tgz"
    version = "0.0.18"

  [[metadata.dependencies]]
    id = "paketo-community/thin"
    sha256 = "95e8020b140ca272f90665a8143e3d5c1a6d9121e7992c932116b7326df513b0"
    source = "https://github.com/paketo-community/thin/archive/v0.0.15.tar.gz"
    source_sha256 = "b0a6aaacc1e9f3ceb5744d506b84fc95b7f4b5a1b1bcb4ef3160f4da3737315c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/thin/releases/download/v0.0.15/thin-0.0.15.tgz"
    version = "0.0.15"

  [[metadata.dependencies]]
    id = "paketo-community/unicorn"
    sha256 = "a1e5b6e5df1c763f4fbe8a44b3f3d1636dc7240c173089c157ffec993df970a2"
    source = "https://github.com/paketo-community/unicorn/archive/v0.0.13.tar.gz"
    source_sha256 = "1eb57ca6a9be6129c29e97b8d1f810c20dbb605f1a9ff9f7f759517754954b2b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/unicorn/releases/download/v0.0.13/unicorn-0.0.13.tgz"
    version = "0.0.13"

  [[metadata.dependencies]]
    id = "paketo-community/rackup"
    sha256 = "370cc77023033d1d5655978e0a0525b52fb6e6e0645f095f1e2b713a73530899"
    source = "https://github.com/paketo-community/rackup/archive/v0.0.17.tar.gz"
    source_sha256 = "44fdd24d183342682fe8e7d197736d37c5bb756faeeb936fb624e3e3350a40f4"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/rackup/releases/download/v0.0.17/rackup-0.0.17.tgz"
    version = "0.0.17"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.135"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.122"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.26"

  [[order.group]]
    id = "paketo-community/puma"
    version = "0.0.18"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.135"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.122"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.26"

  [[order.group]]
    id = "paketo-community/thin"
    version = "0.0.15"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.135"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.122"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.26"

  [[order.group]]
    id = "paketo-community/unicorn"
    version = "0.0.13"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.135"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.122"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.26"

  [[order.group]]
    id = "paketo-community/rackup"
    version = "0.0.17"
