api = "0.2"

[buildpack]
  id = "paketo-community/ruby"
  name = "Ruby Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/mri"
    sha256 = "0dbaf9ee3ba9897f5b9ebedbe54a0bb6f8b8aa14320d131070ae10ba460a1810"
    source = "https://github.com/paketo-community/mri/archive/v0.0.121.tar.gz"
    source_sha256 = "331359db395f73cd4d3302601c1bf1ee9f0c24d8e3edee949e5258e5dbcd5c25"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/mri/releases/download/v0.0.121/mri-0.0.121.tgz"
    version = "0.0.121"

  [[metadata.dependencies]]
    id = "paketo-community/bundler"
    sha256 = "6deb03db02bfc9b7f078b8edd8092378cd47dd96190a36d398c4fd8ad6051ebd"
    source = "https://github.com/paketo-community/bundler/archive/v0.0.107.tar.gz"
    source_sha256 = "105d1eca102128f7274d8be6632015548e7f8f2b922fec0ecaa63cb11165765f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/bundler/releases/download/v0.0.107/bundler-0.0.107.tgz"
    version = "0.0.107"

  [[metadata.dependencies]]
    id = "paketo-community/bundle-install"
    sha256 = "c7245eba62bdddea378aa799a279df37f165752b7666c9aedd10e35b352d1ff1"
    source = "https://github.com/paketo-community/bundle-install/archive/v0.0.11.tar.gz"
    source_sha256 = "6b25edb2529ed713d4836462d37b22575cd536997f2aa063787b4d51c4e0b440"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/bundle-install/releases/download/v0.0.11/bundle-install-0.0.11.tgz"
    version = "0.0.11"

  [[metadata.dependencies]]
    id = "paketo-community/puma"
    sha256 = "fc710b8d839a01bda1038b789dc453c5e622bf583d6f81f8ee4bdd04d4658198"
    source = "https://github.com/paketo-community/puma/archive/v0.0.3.tar.gz"
    source_sha256 = "510b2a546c6ae3a10fb9b6cfacee0f1508b18a1ce9c6e8160c3747f23cc02115"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/puma/releases/download/v0.0.3/puma-0.0.3.tgz"
    version = "0.0.3"

  [[metadata.dependencies]]
    id = "paketo-community/rackup"
    sha256 = "aac73f623027fe04331ae65277e8fc7c0fa5484dc317306e11fa21f479965519"
    source = "https://github.com/paketo-community/rackup/archive/v0.0.2.tar.gz"
    source_sha256 = "47d905de0cf7444fb58f393f452fe98451db3f0d87f80886258fe07ee7cba9fd"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/rackup/releases/download/v0.0.2/rackup-0.0.2.tgz"
    version = "0.0.2"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.121"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.107"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.11"

  [[order.group]]
    id = "paketo-community/puma"
    version = "0.0.3"
