api = "0.2"

[buildpack]
  id = "paketo-community/ruby"
  name = "Ruby Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/mri"
    sha256 = "2ffc8a055f7a7f4d90ab1acdc1a99fddb5b7f0e6a87a53ba850d1d66afa9dbbb"
    source = "https://github.com/paketo-community/mri/archive/v0.0.137.tar.gz"
    source_sha256 = "64c5901b744fcf70053c0f630b06e8a7c64f5fb23170374377c4527b05e9f7a2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/mri/releases/download/v0.0.137/mri-0.0.137.tgz"
    version = "0.0.137"

  [[metadata.dependencies]]
    id = "paketo-community/bundler"
    sha256 = "71f2c48301ecdb24eb151f021848df3baa80441e299539ee724e3cd5841f329c"
    source = "https://github.com/paketo-community/bundler/archive/v0.0.121.tar.gz"
    source_sha256 = "9f281777daf321edcb54c0e64051ae774d545d81345ef4e1b7d3e3863d893549"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/bundler/releases/download/v0.0.121/bundler-0.0.121.tgz"
    version = "0.0.121"

  [[metadata.dependencies]]
    id = "paketo-community/bundle-install"
    sha256 = "19c7684de5c5f4d445b70fc2b39de960aef041111e471eb3569264129c6f9105"
    source = "https://github.com/paketo-community/bundle-install/archive/v0.0.26.tar.gz"
    source_sha256 = "dfe99a4deda10ecdc0495331caccc83a250b354f1f84d6369036e336bfde6735"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/bundle-install/releases/download/v0.0.26/bundle-install-0.0.26.tgz"
    version = "0.0.26"

  [[metadata.dependencies]]
    id = "paketo-community/puma"
    sha256 = "3c568f12bdb81dcbb87cc602937df460c5e1b570bcad6cedadfe1c27b38faa8a"
    source = "https://github.com/paketo-community/puma/archive/v0.0.18.tar.gz"
    source_sha256 = "450c42c9913115c58fad0db1392376179c1d05ffb5f9a4a3e065aaf7a6a0f797"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/puma/releases/download/v0.0.18/puma-0.0.18.tgz"
    version = "0.0.18"

  [[metadata.dependencies]]
    id = "paketo-community/thin"
    sha256 = "95e8020b140ca272f90665a8143e3d5c1a6d9121e7992c932116b7326df513b0"
    source = "https://github.com/paketo-community/thin/archive/v0.0.15.tar.gz"
    source_sha256 = "b0a6aaacc1e9f3ceb5744d506b84fc95b7f4b5a1b1bcb4ef3160f4da3737315c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/thin/releases/download/v0.0.15/thin-0.0.15.tgz"
    version = "0.0.15"

  [[metadata.dependencies]]
    id = "paketo-community/unicorn"
    sha256 = "f69154a355e297de6c9ad135118dd5497fef5af8c6aeb6eb44907c9b2419d377"
    source = "https://github.com/paketo-community/unicorn/archive/v0.0.15.tar.gz"
    source_sha256 = "78d0b13b598115a21fca662ccbb109848757d5feb747525a61e0a564091000de"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/unicorn/releases/download/v0.0.15/unicorn-0.0.15.tgz"
    version = "0.0.15"

  [[metadata.dependencies]]
    id = "paketo-community/rackup"
    sha256 = "370cc77023033d1d5655978e0a0525b52fb6e6e0645f095f1e2b713a73530899"
    source = "https://github.com/paketo-community/rackup/archive/v0.0.17.tar.gz"
    source_sha256 = "44fdd24d183342682fe8e7d197736d37c5bb756faeeb936fb624e3e3350a40f4"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/rackup/releases/download/v0.0.17/rackup-0.0.17.tgz"
    version = "0.0.17"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.137"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.121"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.26"

  [[order.group]]
    id = "paketo-community/puma"
    version = "0.0.18"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.137"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.121"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.26"

  [[order.group]]
    id = "paketo-community/thin"
    version = "0.0.15"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.137"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.121"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.26"

  [[order.group]]
    id = "paketo-community/unicorn"
    version = "0.0.15"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.137"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.121"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.26"

  [[order.group]]
    id = "paketo-community/rackup"
    version = "0.0.17"
