api = "0.2"

[buildpack]
  id = "paketo-community/ruby"
  name = "Ruby Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/mri"
    sha256 = "0cbeadd45c49645bfa9ab831c4e358ac18a13911d599a6ab8c07d9a2335bdf80"
    source = "https://github.com/paketo-community/mri/archive/v0.0.128.tar.gz"
    source_sha256 = "f4d4d2451e92ba44f610ce5c13b68b4a856af7c65c1fb6e1b63b9f09f5e51f94"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/mri/releases/download/v0.0.128/mri-0.0.128.tgz"
    version = "0.0.128"

  [[metadata.dependencies]]
    id = "paketo-community/bundler"
    sha256 = "ddd4e20c2d3d1042e5b20da1dab38fb69143795bf09481be135037ea81d0fa20"
    source = "https://github.com/paketo-community/bundler/archive/v0.0.112.tar.gz"
    source_sha256 = "489bdcd8d37fef39b774c9bd9d621789db974bdc2f37f86376a2ba9e212d5048"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/bundler/releases/download/v0.0.112/bundler-0.0.112.tgz"
    version = "0.0.112"

  [[metadata.dependencies]]
    id = "paketo-community/bundle-install"
    sha256 = "03a93209ff8505f0999369677610497ee771376a6966667dbc7f71a580358653"
    source = "https://github.com/paketo-community/bundle-install/archive/v0.0.17.tar.gz"
    source_sha256 = "ad02fd9eb4aa530a61aba6fb50ec428717bc72dd021de559652042290784701a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/bundle-install/releases/download/v0.0.17/bundle-install-0.0.17.tgz"
    version = "0.0.17"

  [[metadata.dependencies]]
    id = "paketo-community/puma"
    sha256 = "cf3723113e4e4cc2bc2165f539131c1b6384dc57e6d9d48072d66425a4ee8ab5"
    source = "https://github.com/paketo-community/puma/archive/v0.0.9.tar.gz"
    source_sha256 = "a2134440d115cc5836ac6404d482ae8b311df3321b5f7c04dc9b5cb89dca622d"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/puma/releases/download/v0.0.9/puma-0.0.9.tgz"
    version = "0.0.9"

  [[metadata.dependencies]]
    id = "paketo-community/thin"
    sha256 = "4e63b0286b85a3bc6ca85e2ac94369c7b06ec2b007a6b2ea4215c750812e919a"
    source = "https://github.com/paketo-community/thin/archive/v0.0.7.tar.gz"
    source_sha256 = "e364e655b846e446c2c8de653e7d9b97b3d5ef35d288c363f32ada7e8c54499c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/thin/releases/download/v0.0.7/thin-0.0.7.tgz"
    version = "0.0.7"

  [[metadata.dependencies]]
    id = "paketo-community/unicorn"
    sha256 = "b3680971f6538c382edbaf30475992aa5cd986040f27a9fede40bae340492a3b"
    source = "https://github.com/paketo-community/unicorn/archive/v0.0.3.tar.gz"
    source_sha256 = "e094a7a522013e22b453d743c18d97d60994f51cc3611ed86df72180adcba95f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/unicorn/releases/download/v0.0.3/unicorn-0.0.3.tgz"
    version = "0.0.3"

  [[metadata.dependencies]]
    id = "paketo-community/rackup"
    sha256 = "3063a7e64e469519b8baffe2efbbe8aa9b9c1ab2c6891e1b602b71a13eb299e2"
    source = "https://github.com/paketo-community/rackup/archive/v0.0.4.tar.gz"
    source_sha256 = "8b5c0e57f6b040ec3d7d06b6862b77c4e34ccfc00adfa340f17dae2f8a1eed4a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/rackup/releases/download/v0.0.4/rackup-0.0.4.tgz"
    version = "0.0.4"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.128"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.112"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.17"

  [[order.group]]
    id = "paketo-community/puma"
    version = "0.0.9"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.128"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.112"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.17"

  [[order.group]]
    id = "paketo-community/thin"
    version = "0.0.7"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.128"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.112"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.17"

  [[order.group]]
    id = "paketo-community/unicorn"
    version = "0.0.3"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.128"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.112"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.17"

  [[order.group]]
    id = "paketo-community/rackup"
    version = "0.0.4"
