api = "0.2"

[buildpack]
  id = "paketo-community/ruby"
  name = "Ruby Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/mri"
    sha256 = "a3162d734c9beca7e6d19ba1f44fb264b4c55888e3a7bfb4770d578cda539494"
    source = "https://github.com/paketo-community/mri/archive/v0.0.117.tar.gz"
    source_sha256 = "3b1ebb80583ec247ea665138d608cf60c8f69e4ba0cad5a0cb1fafa24c7f4fc9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/mri/releases/download/v0.0.117/mri-0.0.117.tgz"
    version = "0.0.117"

  [[metadata.dependencies]]
    id = "paketo-community/bundler"
    sha256 = "fc5a4c6790a6b162c272edc8ae67de3a42ccca242936d2d47191659a50a030f0"
    source = "https://github.com/paketo-community/bundler/archive/v0.0.102.tar.gz"
    source_sha256 = "e15ad2a9fe9fee90cb02797cf2da7e10ec0c9e0a5b2926822c9ad008a4eb5276"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/bundler/releases/download/v0.0.102/bundler-0.0.102.tgz"
    version = "0.0.102"

  [[metadata.dependencies]]
    id = "paketo-community/bundle-install"
    sha256 = "8ead0be0153850d20792a0d9c32361a6a9c467f8f10cb232ba9afe80386bede2"
    source = "https://github.com/paketo-community/bundle-install/archive/v0.0.7.tar.gz"
    source_sha256 = "57723cf79e0a82e9eeeb4c3d47768e2adc799a968a9cb1450a05eecf52841a9a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/bundle-install/releases/download/v0.0.7/bundle-install-0.0.7.tgz"
    version = "0.0.7"

  [[metadata.dependencies]]
    id = "paketo-community/puma"
    sha256 = "6ea09c2d36af9c31f78fc3beaf471389f1f8035d84c47d165d181fe773df42e4"
    source = "https://github.com/paketo-community/puma/archive/v0.0.3.tar.gz"
    source_sha256 = "35026027b227e4a75dc5c9022f78d1925ca16a86e4b4d24b85db971cd19bdef1"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/puma/releases/download/v0.0.3/puma-0.0.3.tgz"
    version = "0.0.3"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.117"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.102"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.7"

  [[order.group]]
    id = "paketo-community/puma"
    version = "0.0.3"
