api = "0.2"

[buildpack]
  id = "paketo-community/ruby"
  name = "Ruby Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/mri"
    sha256 = "fa6837e1c39eee12013604d8a477925fbbbb6269d7ebd2b549bf9a4924fee567"
    source = "https://github.com/paketo-community/mri/archive/v0.0.122.tar.gz"
    source_sha256 = "5625df7e65d29001e7d8f6e1ad74d72280a2a6c740be13f2e89c1079cc7d7a29"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/mri/releases/download/v0.0.122/mri-0.0.122.tgz"
    version = "0.0.122"

  [[metadata.dependencies]]
    id = "paketo-community/bundler"
    sha256 = "cb726af3361dc12987d1f8055a58d5a00046b8c9321386a37fbaea6431cc6941"
    source = "https://github.com/paketo-community/bundler/archive/v0.0.108.tar.gz"
    source_sha256 = "0f816d71dff5d7100bd9220fad7c14d10e7b9e40b73fcf9f35c7a526c238d3db"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/bundler/releases/download/v0.0.108/bundler-0.0.108.tgz"
    version = "0.0.108"

  [[metadata.dependencies]]
    id = "paketo-community/bundle-install"
    sha256 = "caa666a27ebd96920576554eaf7a308a0e6d6d8da8b3fae2f0c252882fd1b837"
    source = "https://github.com/paketo-community/bundle-install/archive/v0.0.12.tar.gz"
    source_sha256 = "878e3c3d20fc0258ab1b6295a991ecbd77d1dad9a73d8bccff4c41a47a0fdf67"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/bundle-install/releases/download/v0.0.12/bundle-install-0.0.12.tgz"
    version = "0.0.12"

  [[metadata.dependencies]]
    id = "paketo-community/puma"
    sha256 = "5f8e4dc7a87a35d15932050992e10512bcecf0eb8b73b7aa57bfc83bffa87a6e"
    source = "https://github.com/paketo-community/puma/archive/v0.0.6.tar.gz"
    source_sha256 = "235db4176b6662606cc4e25d5115990aa5de2a854691bac13e21d8a541b5ab59"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/puma/releases/download/v0.0.6/puma-0.0.6.tgz"
    version = "0.0.6"

  [[metadata.dependencies]]
    id = "paketo-community/thin"
    sha256 = "08544af82190b6bc2b3925d55d7df4693d1c2028218e93e90b2393b12ec910fa"
    source = "https://github.com/paketo-community/thin/archive/v0.0.1.tar.gz"
    source_sha256 = "1c353e54b223567b28c0420f0ccb3f64e2bc9db1fa317dfa4af5e7ab5b9c7304"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/thin/releases/download/v0.0.1/thin-0.0.1.tgz"
    version = "0.0.1"

  [[metadata.dependencies]]
    id = "paketo-community/unicorn"
    sha256 = "b3680971f6538c382edbaf30475992aa5cd986040f27a9fede40bae340492a3b"
    source = "https://github.com/paketo-community/unicorn/archive/v0.0.3.tar.gz"
    source_sha256 = "e094a7a522013e22b453d743c18d97d60994f51cc3611ed86df72180adcba95f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/unicorn/releases/download/v0.0.3/unicorn-0.0.3.tgz"
    version = "0.0.3"

  [[metadata.dependencies]]
    id = "paketo-community/rackup"
    sha256 = "3063a7e64e469519b8baffe2efbbe8aa9b9c1ab2c6891e1b602b71a13eb299e2"
    source = "https://github.com/paketo-community/rackup/archive/v0.0.4.tar.gz"
    source_sha256 = "8b5c0e57f6b040ec3d7d06b6862b77c4e34ccfc00adfa340f17dae2f8a1eed4a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/rackup/releases/download/v0.0.4/rackup-0.0.4.tgz"
    version = "0.0.4"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.122"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.108"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.12"

  [[order.group]]
    id = "paketo-community/puma"
    version = "0.0.6"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.122"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.108"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.12"

  [[order.group]]
    id = "paketo-community/thin"
    version = "0.0.1"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.122"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.108"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.12"

  [[order.group]]
    id = "paketo-community/unicorn"
    version = "0.0.3"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.122"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.108"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.12"

  [[order.group]]
    id = "paketo-community/rackup"
    version = "0.0.4"
