api = "0.2"

[buildpack]
  id = "paketo-community/ruby"
  name = "Ruby Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/mri"
    sha256 = "0dbaf9ee3ba9897f5b9ebedbe54a0bb6f8b8aa14320d131070ae10ba460a1810"
    source = "https://github.com/paketo-community/mri/archive/v0.0.121.tar.gz"
    source_sha256 = "331359db395f73cd4d3302601c1bf1ee9f0c24d8e3edee949e5258e5dbcd5c25"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/mri/releases/download/v0.0.121/mri-0.0.121.tgz"
    version = "0.0.121"

  [[metadata.dependencies]]
    id = "paketo-community/bundler"
    sha256 = "cb726af3361dc12987d1f8055a58d5a00046b8c9321386a37fbaea6431cc6941"
    source = "https://github.com/paketo-community/bundler/archive/v0.0.108.tar.gz"
    source_sha256 = "0f816d71dff5d7100bd9220fad7c14d10e7b9e40b73fcf9f35c7a526c238d3db"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/bundler/releases/download/v0.0.108/bundler-0.0.108.tgz"
    version = "0.0.108"

  [[metadata.dependencies]]
    id = "paketo-community/bundle-install"
    sha256 = "c7245eba62bdddea378aa799a279df37f165752b7666c9aedd10e35b352d1ff1"
    source = "https://github.com/paketo-community/bundle-install/archive/v0.0.11.tar.gz"
    source_sha256 = "6b25edb2529ed713d4836462d37b22575cd536997f2aa063787b4d51c4e0b440"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/bundle-install/releases/download/v0.0.11/bundle-install-0.0.11.tgz"
    version = "0.0.11"

  [[metadata.dependencies]]
    id = "paketo-community/puma"
    sha256 = "38ef27652984100d9a4c1880d85df8acea4f6699f2a5fa08be398129e0170a12"
    source = "https://github.com/paketo-community/puma/archive/v0.0.5.tar.gz"
    source_sha256 = "dc49050b3fb25514ef814875479f8b85c76a4c4a9d501c1405f4ec6c27c06740"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/puma/releases/download/v0.0.5/puma-0.0.5.tgz"
    version = "0.0.5"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.121"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.108"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.11"

  [[order.group]]
    id = "paketo-community/puma"
    version = "0.0.5"
