api = "0.2"

[buildpack]
  id = "paketo-community/ruby"
  name = "Ruby Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/mri"
    sha256 = "1e2d651641ce28b29174f8a5895019f679f82b499761847bb00a9160a1be30a6"
    source = "https://github.com/paketo-community/mri/archive/v0.0.130.tar.gz"
    source_sha256 = "af07d8ea54050b42b7f3cfda8d23caa182d49d61223576ee11e58b8840bc0e9c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/mri/releases/download/v0.0.130/mri-0.0.130.tgz"
    version = "0.0.130"

  [[metadata.dependencies]]
    id = "paketo-community/bundler"
    sha256 = "de88cb20f37805bbd8641482dfed44c72ea976db2a95f732121c9185d55e4ed1"
    source = "https://github.com/paketo-community/bundler/archive/v0.0.117.tar.gz"
    source_sha256 = "f5956751f51bbdcee9390af1193534cda5ec0d58de7605c93d9275df91f3e3f7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/bundler/releases/download/v0.0.117/bundler-0.0.117.tgz"
    version = "0.0.117"

  [[metadata.dependencies]]
    id = "paketo-community/bundle-install"
    sha256 = "f6132b2540d80547db187a1cbb88b530e3d26f5469529a988c065f37b92faba4"
    source = "https://github.com/paketo-community/bundle-install/archive/v0.0.22.tar.gz"
    source_sha256 = "1e9c96308a1e18c04868ec001128db981da935b625ecb86a673ecccef4cba017"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/bundle-install/releases/download/v0.0.22/bundle-install-0.0.22.tgz"
    version = "0.0.22"

  [[metadata.dependencies]]
    id = "paketo-community/puma"
    sha256 = "c9e64bd914350b6b9f4c7d87aa5df6bf5a40c38473982d860c3424aa88c03973"
    source = "https://github.com/paketo-community/puma/archive/v0.0.13.tar.gz"
    source_sha256 = "1d0afdfab711780ac6addb5153489090b240160a7519e322c438c101a62ee401"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/puma/releases/download/v0.0.13/puma-0.0.13.tgz"
    version = "0.0.13"

  [[metadata.dependencies]]
    id = "paketo-community/thin"
    sha256 = "70b0bb10ba451f2b0c38088cf1e8ecda58040970579e35bcf48a0db9956d3a5c"
    source = "https://github.com/paketo-community/thin/archive/v0.0.11.tar.gz"
    source_sha256 = "5174d80ac23506aebc4129fc0d007158baaa93ccaee9c8f197c20829bb3a3943"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/thin/releases/download/v0.0.11/thin-0.0.11.tgz"
    version = "0.0.11"

  [[metadata.dependencies]]
    id = "paketo-community/unicorn"
    sha256 = "2ef228ef60f0b9eb71bb0e3aed3adb41b55775dbd3d0e9fdc0876bfb7d8125a9"
    source = "https://github.com/paketo-community/unicorn/archive/v0.0.8.tar.gz"
    source_sha256 = "4761e7d1cee2e4f7cf49265be744fcf1a732ce45d513e2373ad8cd9ead15b645"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/unicorn/releases/download/v0.0.8/unicorn-0.0.8.tgz"
    version = "0.0.8"

  [[metadata.dependencies]]
    id = "paketo-community/rackup"
    sha256 = "10d122b62bcfa2f8b271f14bdf1b3b2e743b12486c7085fd1f6536ba4f4a0085"
    source = "https://github.com/paketo-community/rackup/archive/v0.0.11.tar.gz"
    source_sha256 = "6d2aa3aefe3cb0fc9bd5169b5a8ffe9840aa40d6b8afff2c69ab9b32d25b670f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/rackup/releases/download/v0.0.11/rackup-0.0.11.tgz"
    version = "0.0.11"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.130"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.117"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.22"

  [[order.group]]
    id = "paketo-community/puma"
    version = "0.0.13"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.130"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.117"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.22"

  [[order.group]]
    id = "paketo-community/thin"
    version = "0.0.11"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.130"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.117"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.22"

  [[order.group]]
    id = "paketo-community/unicorn"
    version = "0.0.8"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.130"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.117"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.22"

  [[order.group]]
    id = "paketo-community/rackup"
    version = "0.0.11"
