api = "0.2"

[buildpack]
  id = "paketo-community/ruby"
  name = "Ruby Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/mri"
    sha256 = "5b83df571dccf44fd9fe04d0780cf3b1b0304e0d6873859a40e6633c70c2500b"
    source = "https://github.com/paketo-community/mri/archive/v0.0.124.tar.gz"
    source_sha256 = "51cff4362d7879cf68f17dbb9d990168d200ae9d6a933ac1bb38ef071a3489ab"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/mri/releases/download/v0.0.124/mri-0.0.124.tgz"
    version = "0.0.124"

  [[metadata.dependencies]]
    id = "paketo-community/bundler"
    sha256 = "4948407f832a7dae2559a53a463a6ea052ed9fbd469a48475f91dfdac3b6bf65"
    source = "https://github.com/paketo-community/bundler/archive/v0.0.110.tar.gz"
    source_sha256 = "3031b41ce7861bef8d775fcd1686ba6a3ca90bcdbf41a804cbcd2f0c75b68629"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/bundler/releases/download/v0.0.110/bundler-0.0.110.tgz"
    version = "0.0.110"

  [[metadata.dependencies]]
    id = "paketo-community/bundle-install"
    sha256 = "360af1e2d827a02a35e3d00ac26a4292e1b3fe9a8741850882e758dd7f5277e0"
    source = "https://github.com/paketo-community/bundle-install/archive/v0.0.15.tar.gz"
    source_sha256 = "5f02d96eb3e8df4129af240156258426bd64e26a2ef4d577494b52a816b3e1c5"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/bundle-install/releases/download/v0.0.15/bundle-install-0.0.15.tgz"
    version = "0.0.15"

  [[metadata.dependencies]]
    id = "paketo-community/puma"
    sha256 = "647f049ae38e99f1364c2d06a0965a40b1b7b98744b3e586dae6bf9947a0af9a"
    source = "https://github.com/paketo-community/puma/archive/v0.0.7.tar.gz"
    source_sha256 = "3f80f7e38664a4908f59052b6eb13d7c0cc262b53d09c0c201eacc4016867642"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/puma/releases/download/v0.0.7/puma-0.0.7.tgz"
    version = "0.0.7"

  [[metadata.dependencies]]
    id = "paketo-community/thin"
    sha256 = "8f410cb5274ca6d8f0bcf73711e08b0df7da10d0c4b34c5981316402fe0704c3"
    source = "https://github.com/paketo-community/thin/archive/v0.0.3.tar.gz"
    source_sha256 = "01a8460378c7b83d2b0ddfb65ed4cee3a14786009f5fe73015d636bf7a09dc6e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/thin/releases/download/v0.0.3/thin-0.0.3.tgz"
    version = "0.0.3"

  [[metadata.dependencies]]
    id = "paketo-community/unicorn"
    sha256 = "b3680971f6538c382edbaf30475992aa5cd986040f27a9fede40bae340492a3b"
    source = "https://github.com/paketo-community/unicorn/archive/v0.0.3.tar.gz"
    source_sha256 = "e094a7a522013e22b453d743c18d97d60994f51cc3611ed86df72180adcba95f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/unicorn/releases/download/v0.0.3/unicorn-0.0.3.tgz"
    version = "0.0.3"

  [[metadata.dependencies]]
    id = "paketo-community/rackup"
    sha256 = "3063a7e64e469519b8baffe2efbbe8aa9b9c1ab2c6891e1b602b71a13eb299e2"
    source = "https://github.com/paketo-community/rackup/archive/v0.0.4.tar.gz"
    source_sha256 = "8b5c0e57f6b040ec3d7d06b6862b77c4e34ccfc00adfa340f17dae2f8a1eed4a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/rackup/releases/download/v0.0.4/rackup-0.0.4.tgz"
    version = "0.0.4"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.124"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.110"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.15"

  [[order.group]]
    id = "paketo-community/puma"
    version = "0.0.7"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.124"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.110"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.15"

  [[order.group]]
    id = "paketo-community/thin"
    version = "0.0.3"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.124"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.110"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.15"

  [[order.group]]
    id = "paketo-community/unicorn"
    version = "0.0.3"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.124"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.110"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.15"

  [[order.group]]
    id = "paketo-community/rackup"
    version = "0.0.4"
