api = "0.2"

[buildpack]
  id = "paketo-community/ruby"
  name = "Ruby Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/mri"
    sha256 = "0cbeadd45c49645bfa9ab831c4e358ac18a13911d599a6ab8c07d9a2335bdf80"
    source = "https://github.com/paketo-community/mri/archive/v0.0.128.tar.gz"
    source_sha256 = "f4d4d2451e92ba44f610ce5c13b68b4a856af7c65c1fb6e1b63b9f09f5e51f94"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/mri/releases/download/v0.0.128/mri-0.0.128.tgz"
    version = "0.0.128"

  [[metadata.dependencies]]
    id = "paketo-community/bundler"
    sha256 = "93c07bdf87cee5fbcdac9abe1a7ae2b6f76cdba37cfdcdcdbe2d586e325f48ea"
    source = "https://github.com/paketo-community/bundler/archive/v0.0.114.tar.gz"
    source_sha256 = "590628491df8d1335a139b7f717538244def6ba18be94d2575a30ba87989029f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/bundler/releases/download/v0.0.114/bundler-0.0.114.tgz"
    version = "0.0.114"

  [[metadata.dependencies]]
    id = "paketo-community/bundle-install"
    sha256 = "007cdbbfa603f213d1b36c8226ba69a2019bb739e7a020062db717142739eca3"
    source = "https://github.com/paketo-community/bundle-install/archive/v0.0.18.tar.gz"
    source_sha256 = "d449a22a0d91addacfa940a7598d79949048f0dcf2748f7a0ed7f34505e071a1"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/bundle-install/releases/download/v0.0.18/bundle-install-0.0.18.tgz"
    version = "0.0.18"

  [[metadata.dependencies]]
    id = "paketo-community/puma"
    sha256 = "6a4031dbf0af34065956781100a8a460b62fc7ffb9d4c523f2b9ea53d9b0418e"
    source = "https://github.com/paketo-community/puma/archive/v0.0.12.tar.gz"
    source_sha256 = "8c0da39bd730b253794bcf6ad344f2832b01301b796fb8c56e238e4ca79a3c95"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/puma/releases/download/v0.0.12/puma-0.0.12.tgz"
    version = "0.0.12"

  [[metadata.dependencies]]
    id = "paketo-community/thin"
    sha256 = "47fa74b4f86e2c60a111eb18f86ec6fbfc2e7b4649ace7ad1f5942a4539a780a"
    source = "https://github.com/paketo-community/thin/archive/v0.0.8.tar.gz"
    source_sha256 = "ca79941c57796d303069a86efcbb6b2b8e371af55b2b9948c9fb2b3b78e9542c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/thin/releases/download/v0.0.8/thin-0.0.8.tgz"
    version = "0.0.8"

  [[metadata.dependencies]]
    id = "paketo-community/unicorn"
    sha256 = "09bd417d6eeb5093462b3bf91ba82745ab4111b748d73c455e94bcd61d4cafa9"
    source = "https://github.com/paketo-community/unicorn/archive/v0.0.6.tar.gz"
    source_sha256 = "a1a1ed59708fd4b5076612f72e6224be8a65e95eb97afaf843f357974e9cc081"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/unicorn/releases/download/v0.0.6/unicorn-0.0.6.tgz"
    version = "0.0.6"

  [[metadata.dependencies]]
    id = "paketo-community/rackup"
    sha256 = "2817a52d537fad5363e49001cf7633ab6389f2c65ebdaa9d62da5e7a941fe632"
    source = "https://github.com/paketo-community/rackup/archive/v0.0.7.tar.gz"
    source_sha256 = "d517cf91042fc04ac30b222866137e1e30d78127647b2deeec5a368af090efe3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/rackup/releases/download/v0.0.7/rackup-0.0.7.tgz"
    version = "0.0.7"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.128"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.114"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.18"

  [[order.group]]
    id = "paketo-community/puma"
    version = "0.0.12"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.128"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.114"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.18"

  [[order.group]]
    id = "paketo-community/thin"
    version = "0.0.8"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.128"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.114"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.18"

  [[order.group]]
    id = "paketo-community/unicorn"
    version = "0.0.6"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.128"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.114"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.18"

  [[order.group]]
    id = "paketo-community/rackup"
    version = "0.0.7"
