api = "0.2"

[buildpack]
  id = "paketo-community/ruby"
  name = "Ruby Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/mri"
    sha256 = "99d73866d254d12182d0aa063cd31d3b9fe88b4a887480fd1edf64c787795242"
    source = "https://github.com/paketo-community/mri/archive/v0.0.129.tar.gz"
    source_sha256 = "b20407c0ced39855659b562e5ff57ba60b28f668b78cb0cf2c037036dbe567e6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/mri/releases/download/v0.0.129/mri-0.0.129.tgz"
    version = "0.0.129"

  [[metadata.dependencies]]
    id = "paketo-community/bundler"
    sha256 = "11052b13795cc12a4fbb089c5298d1f7e6bbcc6a1d4cec285fdbbbc39fa7a8b0"
    source = "https://github.com/paketo-community/bundler/archive/v0.0.116.tar.gz"
    source_sha256 = "49ff899922bb63891b8301fb7446773269f38514ccaab70e3616aaf7a4724326"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/bundler/releases/download/v0.0.116/bundler-0.0.116.tgz"
    version = "0.0.116"

  [[metadata.dependencies]]
    id = "paketo-community/bundle-install"
    sha256 = "72c620f909d0c0efa58f6101ce2267174b70db862f00a43e3d6a963e7b8fab07"
    source = "https://github.com/paketo-community/bundle-install/archive/v0.0.20.tar.gz"
    source_sha256 = "003d1598aef85d66a6fae17e173d44b6ceb29b026b9010db84a02e9f6cb39708"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/bundle-install/releases/download/v0.0.20/bundle-install-0.0.20.tgz"
    version = "0.0.20"

  [[metadata.dependencies]]
    id = "paketo-community/puma"
    sha256 = "6a4031dbf0af34065956781100a8a460b62fc7ffb9d4c523f2b9ea53d9b0418e"
    source = "https://github.com/paketo-community/puma/archive/v0.0.12.tar.gz"
    source_sha256 = "8c0da39bd730b253794bcf6ad344f2832b01301b796fb8c56e238e4ca79a3c95"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/puma/releases/download/v0.0.12/puma-0.0.12.tgz"
    version = "0.0.12"

  [[metadata.dependencies]]
    id = "paketo-community/thin"
    sha256 = "70b0bb10ba451f2b0c38088cf1e8ecda58040970579e35bcf48a0db9956d3a5c"
    source = "https://github.com/paketo-community/thin/archive/v0.0.11.tar.gz"
    source_sha256 = "5174d80ac23506aebc4129fc0d007158baaa93ccaee9c8f197c20829bb3a3943"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/thin/releases/download/v0.0.11/thin-0.0.11.tgz"
    version = "0.0.11"

  [[metadata.dependencies]]
    id = "paketo-community/unicorn"
    sha256 = "99e2764c400bf9b14150b931eab3e8e5ba2d5e240e2afcac9118d8acad4a2f78"
    source = "https://github.com/paketo-community/unicorn/archive/v0.0.7.tar.gz"
    source_sha256 = "f866a6bd729e3b657d5dda3ea00d8994efc5caa6a30e840bdd818f7008b41d56"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/unicorn/releases/download/v0.0.7/unicorn-0.0.7.tgz"
    version = "0.0.7"

  [[metadata.dependencies]]
    id = "paketo-community/rackup"
    sha256 = "d6305891228aca64ab1d50e29052dd8a8c0816ea9fd30591f31235c100d22f35"
    source = "https://github.com/paketo-community/rackup/archive/v0.0.10.tar.gz"
    source_sha256 = "a3bd3611bc90f450080b419a892371859d4f49b008fc26202f615158ff004bc8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/rackup/releases/download/v0.0.10/rackup-0.0.10.tgz"
    version = "0.0.10"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.129"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.116"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.20"

  [[order.group]]
    id = "paketo-community/puma"
    version = "0.0.12"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.129"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.116"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.20"

  [[order.group]]
    id = "paketo-community/thin"
    version = "0.0.11"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.129"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.116"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.20"

  [[order.group]]
    id = "paketo-community/unicorn"
    version = "0.0.7"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.129"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.116"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.20"

  [[order.group]]
    id = "paketo-community/rackup"
    version = "0.0.10"
