api = "0.2"

[buildpack]
  id = "paketo-community/ruby"
  name = "Ruby Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/mri"
    sha256 = "9141c505d69452f83aab17b2750c844b2f907022eb6bee39446fcd8c539c918f"
    source = "https://github.com/paketo-community/mri/archive/v0.0.141.tar.gz"
    source_sha256 = "bb462c831bc80f7f8a937c3ba5f5204a3c784d1c517d32d4cfbe3af75b24602c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/mri/releases/download/v0.0.141/mri-0.0.141.tgz"
    version = "0.0.141"

  [[metadata.dependencies]]
    id = "paketo-community/bundler"
    sha256 = "6139b43ecc925e29c36a41af28d9b1272e3ecb95289b49351b847d54635a6b31"
    source = "https://github.com/paketo-community/bundler/archive/v0.0.128.tar.gz"
    source_sha256 = "a3f1876b9a8d4cf9c9d0ac8e89a89fe4e54b6a0797b0ae798edae060801fa316"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/bundler/releases/download/v0.0.128/bundler-0.0.128.tgz"
    version = "0.0.128"

  [[metadata.dependencies]]
    id = "paketo-community/bundle-install"
    sha256 = "96af0c756a4eb2b4907fdc013b5f5713a93a5b080a49bf27df7c8de7fe2ea203"
    source = "https://github.com/paketo-community/bundle-install/archive/v0.0.34.tar.gz"
    source_sha256 = "31987873ca2633de310394d21065278531aa1696d1d18801f2ee1a1cfe0d1873"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/bundle-install/releases/download/v0.0.34/bundle-install-0.0.34.tgz"
    version = "0.0.34"

  [[metadata.dependencies]]
    id = "paketo-community/puma"
    sha256 = "e31048ec0afaa1dbee6284b71e874f12fbcd3a71a73888467484f120bea23e68"
    source = "https://github.com/paketo-community/puma/archive/v0.0.22.tar.gz"
    source_sha256 = "32ac75be0ba5bfa2ade73bb7c0805ce70d6817844544a4d1046b4910a8d5636a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/puma/releases/download/v0.0.22/puma-0.0.22.tgz"
    version = "0.0.22"

  [[metadata.dependencies]]
    id = "paketo-community/thin"
    sha256 = "e7621b3ab5c8d3284c17b597d1bd2a05c4f0ea0e4f92583b6db3a0cf6c85e25a"
    source = "https://github.com/paketo-community/thin/archive/v0.0.19.tar.gz"
    source_sha256 = "fdd4e856ff094b954830d7171c09ad3c4affb65a70375de0b46c736594b2d271"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/thin/releases/download/v0.0.19/thin-0.0.19.tgz"
    version = "0.0.19"

  [[metadata.dependencies]]
    id = "paketo-community/unicorn"
    sha256 = "9f246d65e64d28c42ba1de94ce61202f45546dca9ac0c81ba908b88ef3fb3f7f"
    source = "https://github.com/paketo-community/unicorn/archive/v0.0.17.tar.gz"
    source_sha256 = "ad6ae2e0e85029f406e727b98df65cfd9d2ceb471d6792020610ae901ebb9369"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/unicorn/releases/download/v0.0.17/unicorn-0.0.17.tgz"
    version = "0.0.17"

  [[metadata.dependencies]]
    id = "paketo-community/rackup"
    sha256 = "eb42e5e269a6322dc3b83691e4e9e988348d3f44f07327429e3ab5dac6ccecd8"
    source = "https://github.com/paketo-community/rackup/archive/v0.0.23.tar.gz"
    source_sha256 = "bb8562839414d30749e4d1986f1d202c8b8f8473a9b60f2a48e7fca28b739eee"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/rackup/releases/download/v0.0.23/rackup-0.0.23.tgz"
    version = "0.0.23"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.141"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.128"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.34"

  [[order.group]]
    id = "paketo-community/puma"
    version = "0.0.22"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.141"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.128"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.34"

  [[order.group]]
    id = "paketo-community/thin"
    version = "0.0.19"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.141"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.128"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.34"

  [[order.group]]
    id = "paketo-community/unicorn"
    version = "0.0.17"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.141"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.128"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.34"

  [[order.group]]
    id = "paketo-community/rackup"
    version = "0.0.23"
