api = "0.2"

[buildpack]
  id = "paketo-community/ruby"
  name = "Ruby Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/mri"
    sha256 = "5d78738cbb5a312ee85cc420fb7d13994664e55c0eb7c36960c3f0e5bb96f8fc"
    source = "https://github.com/paketo-community/mri/archive/v0.0.126.tar.gz"
    source_sha256 = "e869a98d1f3d84974f6b1faf6efb0339802ce89dff97a083eb83962c9e25e7f5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/mri/releases/download/v0.0.126/mri-0.0.126.tgz"
    version = "0.0.126"

  [[metadata.dependencies]]
    id = "paketo-community/bundler"
    sha256 = "ddd4e20c2d3d1042e5b20da1dab38fb69143795bf09481be135037ea81d0fa20"
    source = "https://github.com/paketo-community/bundler/archive/v0.0.112.tar.gz"
    source_sha256 = "489bdcd8d37fef39b774c9bd9d621789db974bdc2f37f86376a2ba9e212d5048"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/bundler/releases/download/v0.0.112/bundler-0.0.112.tgz"
    version = "0.0.112"

  [[metadata.dependencies]]
    id = "paketo-community/bundle-install"
    sha256 = "03a93209ff8505f0999369677610497ee771376a6966667dbc7f71a580358653"
    source = "https://github.com/paketo-community/bundle-install/archive/v0.0.17.tar.gz"
    source_sha256 = "ad02fd9eb4aa530a61aba6fb50ec428717bc72dd021de559652042290784701a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/bundle-install/releases/download/v0.0.17/bundle-install-0.0.17.tgz"
    version = "0.0.17"

  [[metadata.dependencies]]
    id = "paketo-community/puma"
    sha256 = "36ba3ee18e4fa935259d9a6b0d2255c9b6432f9fa6a20f0b1309512ab9a67c25"
    source = "https://github.com/paketo-community/puma/archive/v0.0.10.tar.gz"
    source_sha256 = "4720064c3f95a41d07f197b0248ea2250c02a155054ddd59e3cdf64371a1da09"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/puma/releases/download/v0.0.10/puma-0.0.10.tgz"
    version = "0.0.10"

  [[metadata.dependencies]]
    id = "paketo-community/thin"
    sha256 = "e01d1d85a10d57e16d99ba20a8e981d0f0888d1d2c7f1e0790e6c8a79c5db193"
    source = "https://github.com/paketo-community/thin/archive/v0.0.6.tar.gz"
    source_sha256 = "16a36d6fb740a0c54882f5cd451c92d547f7840ac6936106327ad1c51b382826"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/thin/releases/download/v0.0.6/thin-0.0.6.tgz"
    version = "0.0.6"

  [[metadata.dependencies]]
    id = "paketo-community/unicorn"
    sha256 = "b3680971f6538c382edbaf30475992aa5cd986040f27a9fede40bae340492a3b"
    source = "https://github.com/paketo-community/unicorn/archive/v0.0.3.tar.gz"
    source_sha256 = "e094a7a522013e22b453d743c18d97d60994f51cc3611ed86df72180adcba95f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/unicorn/releases/download/v0.0.3/unicorn-0.0.3.tgz"
    version = "0.0.3"

  [[metadata.dependencies]]
    id = "paketo-community/rackup"
    sha256 = "3063a7e64e469519b8baffe2efbbe8aa9b9c1ab2c6891e1b602b71a13eb299e2"
    source = "https://github.com/paketo-community/rackup/archive/v0.0.4.tar.gz"
    source_sha256 = "8b5c0e57f6b040ec3d7d06b6862b77c4e34ccfc00adfa340f17dae2f8a1eed4a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/rackup/releases/download/v0.0.4/rackup-0.0.4.tgz"
    version = "0.0.4"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.126"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.112"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.17"

  [[order.group]]
    id = "paketo-community/puma"
    version = "0.0.10"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.126"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.112"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.17"

  [[order.group]]
    id = "paketo-community/thin"
    version = "0.0.6"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.126"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.112"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.17"

  [[order.group]]
    id = "paketo-community/unicorn"
    version = "0.0.3"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.126"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.112"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.17"

  [[order.group]]
    id = "paketo-community/rackup"
    version = "0.0.4"
