api = "0.2"

[buildpack]
  id = "paketo-community/ruby"
  name = "Ruby Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/mri"
    sha256 = "2ffc8a055f7a7f4d90ab1acdc1a99fddb5b7f0e6a87a53ba850d1d66afa9dbbb"
    source = "https://github.com/paketo-community/mri/archive/v0.0.137.tar.gz"
    source_sha256 = "64c5901b744fcf70053c0f630b06e8a7c64f5fb23170374377c4527b05e9f7a2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/mri/releases/download/v0.0.137/mri-0.0.137.tgz"
    version = "0.0.137"

  [[metadata.dependencies]]
    id = "paketo-community/bundler"
    sha256 = "bc21fb54b981b360ed8d5419b20774d09287cdc4399f16021b75a4eba8401017"
    source = "https://github.com/paketo-community/bundler/archive/v0.0.123.tar.gz"
    source_sha256 = "ec1bb67dfb88db5fb20b25a65d5f63826b5ef12cb0756edefec045023369296e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/bundler/releases/download/v0.0.123/bundler-0.0.123.tgz"
    version = "0.0.123"

  [[metadata.dependencies]]
    id = "paketo-community/bundle-install"
    sha256 = "5fca82bee8e92642e40be7f469e534a6747bf99a6e1c342cf2bc9dbd17d814f4"
    source = "https://github.com/paketo-community/bundle-install/archive/v0.0.30.tar.gz"
    source_sha256 = "b26fa237b42accddd57688a5e9f5a2384ae5747bb2ef83ba380d18ddd4f01bd0"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/bundle-install/releases/download/v0.0.30/bundle-install-0.0.30.tgz"
    version = "0.0.30"

  [[metadata.dependencies]]
    id = "paketo-community/puma"
    sha256 = "70e0495456f0d1b1496c1b476adcfbbf45df6f0e92344aefa11978b5b97a2f52"
    source = "https://github.com/paketo-community/puma/archive/v0.0.21.tar.gz"
    source_sha256 = "a34b4166426e85ce09b5abecca37d3271dead6ea87543968c3d81680eae018bf"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/puma/releases/download/v0.0.21/puma-0.0.21.tgz"
    version = "0.0.21"

  [[metadata.dependencies]]
    id = "paketo-community/thin"
    sha256 = "e7621b3ab5c8d3284c17b597d1bd2a05c4f0ea0e4f92583b6db3a0cf6c85e25a"
    source = "https://github.com/paketo-community/thin/archive/v0.0.19.tar.gz"
    source_sha256 = "fdd4e856ff094b954830d7171c09ad3c4affb65a70375de0b46c736594b2d271"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/thin/releases/download/v0.0.19/thin-0.0.19.tgz"
    version = "0.0.19"

  [[metadata.dependencies]]
    id = "paketo-community/unicorn"
    sha256 = "f69154a355e297de6c9ad135118dd5497fef5af8c6aeb6eb44907c9b2419d377"
    source = "https://github.com/paketo-community/unicorn/archive/v0.0.15.tar.gz"
    source_sha256 = "78d0b13b598115a21fca662ccbb109848757d5feb747525a61e0a564091000de"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/unicorn/releases/download/v0.0.15/unicorn-0.0.15.tgz"
    version = "0.0.15"

  [[metadata.dependencies]]
    id = "paketo-community/rackup"
    sha256 = "da9fa563d7aea7eee34e8163d739badee1c65a909f282852a00314d63c614632"
    source = "https://github.com/paketo-community/rackup/archive/v0.0.20.tar.gz"
    source_sha256 = "7fa42831e9686bf2af3c42460ad26c6eb11294eb75cc94a0a40d44e765235515"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/rackup/releases/download/v0.0.20/rackup-0.0.20.tgz"
    version = "0.0.20"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.137"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.123"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.30"

  [[order.group]]
    id = "paketo-community/puma"
    version = "0.0.21"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.137"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.123"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.30"

  [[order.group]]
    id = "paketo-community/thin"
    version = "0.0.19"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.137"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.123"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.30"

  [[order.group]]
    id = "paketo-community/unicorn"
    version = "0.0.15"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.137"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.123"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.30"

  [[order.group]]
    id = "paketo-community/rackup"
    version = "0.0.20"
