api = "0.2"

[buildpack]
  id = "paketo-community/ruby"
  name = "Ruby Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/mri"
    sha256 = "3042bd1566a51e6b54373f8635028602c6750ff7c2a06b33fe3b1012ed7f49fa"
    source = "https://github.com/paketo-community/mri/archive/v0.0.116.tar.gz"
    source_sha256 = "37c56d8f4e416545ebde74921c312d7a2150980ed26086f5b9f4315493eb0a8e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/mri/releases/download/v0.0.116/mri-0.0.116.tgz"
    version = "0.0.116"

  [[metadata.dependencies]]
    id = "paketo-community/bundler"
    sha256 = "fc5a4c6790a6b162c272edc8ae67de3a42ccca242936d2d47191659a50a030f0"
    source = "https://github.com/paketo-community/bundler/archive/v0.0.102.tar.gz"
    source_sha256 = "e15ad2a9fe9fee90cb02797cf2da7e10ec0c9e0a5b2926822c9ad008a4eb5276"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/bundler/releases/download/v0.0.102/bundler-0.0.102.tgz"
    version = "0.0.102"

  [[metadata.dependencies]]
    id = "paketo-community/bundle-install"
    sha256 = "8ead0be0153850d20792a0d9c32361a6a9c467f8f10cb232ba9afe80386bede2"
    source = "https://github.com/paketo-community/bundle-install/archive/v0.0.7.tar.gz"
    source_sha256 = "57723cf79e0a82e9eeeb4c3d47768e2adc799a968a9cb1450a05eecf52841a9a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/bundle-install/releases/download/v0.0.7/bundle-install-0.0.7.tgz"
    version = "0.0.7"

  [[metadata.dependencies]]
    id = "paketo-community/puma"
    sha256 = "fc710b8d839a01bda1038b789dc453c5e622bf583d6f81f8ee4bdd04d4658198"
    source = "https://github.com/paketo-community/puma/archive/v0.0.3.tar.gz"
    source_sha256 = "510b2a546c6ae3a10fb9b6cfacee0f1508b18a1ce9c6e8160c3747f23cc02115"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/puma/releases/download/v0.0.3/puma-0.0.3.tgz"
    version = "0.0.3"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.116"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.102"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.7"

  [[order.group]]
    id = "paketo-community/puma"
    version = "0.0.3"
