api = "0.2"

[buildpack]
  id = "paketo-community/ruby"
  name = "Ruby Buildpack"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-community/mri"
    sha256 = "99d73866d254d12182d0aa063cd31d3b9fe88b4a887480fd1edf64c787795242"
    source = "https://github.com/paketo-community/mri/archive/v0.0.129.tar.gz"
    source_sha256 = "b20407c0ced39855659b562e5ff57ba60b28f668b78cb0cf2c037036dbe567e6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/mri/releases/download/v0.0.129/mri-0.0.129.tgz"
    version = "0.0.129"

  [[metadata.dependencies]]
    id = "paketo-community/bundler"
    sha256 = "de88cb20f37805bbd8641482dfed44c72ea976db2a95f732121c9185d55e4ed1"
    source = "https://github.com/paketo-community/bundler/archive/v0.0.117.tar.gz"
    source_sha256 = "f5956751f51bbdcee9390af1193534cda5ec0d58de7605c93d9275df91f3e3f7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/bundler/releases/download/v0.0.117/bundler-0.0.117.tgz"
    version = "0.0.117"

  [[metadata.dependencies]]
    id = "paketo-community/bundle-install"
    sha256 = "72c620f909d0c0efa58f6101ce2267174b70db862f00a43e3d6a963e7b8fab07"
    source = "https://github.com/paketo-community/bundle-install/archive/v0.0.20.tar.gz"
    source_sha256 = "003d1598aef85d66a6fae17e173d44b6ceb29b026b9010db84a02e9f6cb39708"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/bundle-install/releases/download/v0.0.20/bundle-install-0.0.20.tgz"
    version = "0.0.20"

  [[metadata.dependencies]]
    id = "paketo-community/puma"
    sha256 = "c9e64bd914350b6b9f4c7d87aa5df6bf5a40c38473982d860c3424aa88c03973"
    source = "https://github.com/paketo-community/puma/archive/v0.0.13.tar.gz"
    source_sha256 = "1d0afdfab711780ac6addb5153489090b240160a7519e322c438c101a62ee401"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-community/puma/releases/download/v0.0.13/puma-0.0.13.tgz"
    version = "0.0.13"

  [[metadata.dependencies]]
    id = "paketo-community/thin"
    sha256 = "519bf711a3bad56990a03e22a582004f130b2b72457dd68d91e8dc3d1dca31eb"
    source = "https://github.com/paketo-community/thin/archive/v0.0.10.tar.gz"
    source_sha256 = "8a5c10d4704b30c9dbf15f50486827bdebc2cef5898049178abdbcb8fd9c8fdc"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/thin/releases/download/v0.0.10/thin-0.0.10.tgz"
    version = "0.0.10"

  [[metadata.dependencies]]
    id = "paketo-community/unicorn"
    sha256 = "99e2764c400bf9b14150b931eab3e8e5ba2d5e240e2afcac9118d8acad4a2f78"
    source = "https://github.com/paketo-community/unicorn/archive/v0.0.7.tar.gz"
    source_sha256 = "f866a6bd729e3b657d5dda3ea00d8994efc5caa6a30e840bdd818f7008b41d56"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/unicorn/releases/download/v0.0.7/unicorn-0.0.7.tgz"
    version = "0.0.7"

  [[metadata.dependencies]]
    id = "paketo-community/rackup"
    sha256 = "d6305891228aca64ab1d50e29052dd8a8c0816ea9fd30591f31235c100d22f35"
    source = "https://github.com/paketo-community/rackup/archive/v0.0.10.tar.gz"
    source_sha256 = "a3bd3611bc90f450080b419a892371859d4f49b008fc26202f615158ff004bc8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/rackup/releases/download/v0.0.10/rackup-0.0.10.tgz"
    version = "0.0.10"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.129"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.117"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.20"

  [[order.group]]
    id = "paketo-community/puma"
    version = "0.0.13"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.129"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.117"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.20"

  [[order.group]]
    id = "paketo-community/thin"
    version = "0.0.10"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.129"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.117"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.20"

  [[order.group]]
    id = "paketo-community/unicorn"
    version = "0.0.7"

[[order]]

  [[order.group]]
    id = "paketo-community/mri"
    version = "0.0.129"

  [[order.group]]
    id = "paketo-community/bundler"
    version = "0.0.117"

  [[order.group]]
    id = "paketo-community/bundle-install"
    version = "0.0.20"

  [[order.group]]
    id = "paketo-community/rackup"
    version = "0.0.10"
